site_name: Введение в машинное и глубокое обучение
site_url: https://ai-mai-307.github.io/ml-dl-course-site/
theme:
  name: material
  language: ru
plugins:
  - search
  - mkdocs-jupyter
  - table-reader:
      data_path: docs/assets/data   
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js   
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Главная: index.md
  - Инструкции:
    - Запись на курс: index/assign_course.md
    - Как успешно пройти курс: index/complete_course_instructionds.md
    - Работа с GitHub Classroom: index/github_classroom_instructions.md
    - Работа с Yandex Datasphere: index/datasphere_unstructions.md
    - Работа на локальной машине: index/local_machine_instructions.md

  - Классическое машинное обучение:
      - О курсе: ml/index.md
      - Конспекты:
        - Лекция №1. Первое знакомство с машинным обучением: ml/lecture_01.md
      - Домашние задания:
        - №1. Предвариетельный анализ данных: ml/hw_01.md
  - Глубокое машинное обучение:
      - О курсе: dl/index.md
      - Конспекты: 
        - Лекция №1. Основные понятия глубокого обучения: dl/lecture_01.md
      - Домашние задания: dl/hw.md
