site_name: Введение в машинное и глубокое обучение
site_url: https://ai-mai-307.github.io/ml-dl-course-site/
theme:
  name: material
  language: ru
plugins:
  - search
  - mkdocs-jupyter
  - table-reader:
      data_path: docs/assets/data   
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js   
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Главная: index.md
  - Расписание: index/schedule.md
  - Инструкции:
    - Запись на курс: index/assign_course.md
    - Как успешно пройти курс: index/complete_course_instructionds.md
    - Добросовестное использование LLM: index/llm_rules.md
    - Как принять задания в GitHub Classroom: index/howtoclassroom.md
    - Как работать с агентом-кодревьювером: index/work_with_agent.md
    - Yandex Datasphere:
      - Как склонировать репозиторий: index/clone_repo.md
      - Как работать с датасетами: index/what_is_dataset.md
      - Как контролировать расходы: index/manage_budget.md

  - Классическое машинное обучение:
      - О курсе: ml/index.md
      - Конспекты:
        - Лекция №1. Первое знакомство с машинным обучением: ml/lecture_01.md
        - Лекция №2. Предварительная обработка данных: ml/lecture_02.md
      - Домашние задания:
        - №1. Предвариетельный анализ данных: ml/hw_01.md
  - Глубокое машинное обучение:
      - О курсе: dl/index.md
      - Конспекты: 
        - Лекция №1. Основные понятия глубокого обучения: dl/lecture_01.md
        - Лекция №2. Обработка изображений с помощью глубокого обучения: dl/lecture_02.md
        - Лекция №3. Обработка аудиосигнала с помощью глубокого оубчения: dl/lecture_03.md
      - Домашние задания:
        - №1. Обучение многослойного персептрона: dl/hw_01.md
